name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  plugin_test:
    name: asdf plugin test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: asdf_plugin_test
        # FIXME: https://github.com/asdf-vm/actions/issues/599
        uses: asdf-vm/actions/plugin-test@v3
        with:
          command: podman --version
